### PR TITLE
Restore options prop

### LINKED ISSUE #56: How to set the <LMarker> riseOnHover option?
Does vue-leaflet have no options prop?  
`<LMarker :options="{riseOnHover: true, riseOffset: 300}"/>`， Vue2-leaflet style doesn't seem to work.

### PR DESCRIPTION
**Pull request by DonNicoJs**
fixes #56 

Some considerations.

`setOptions` used in `Vue2Leaflet` does.. nothing reactively! Each map element should be re-instantiated to pickup the behaviour (as per my tests) we also keep saying to people that the options are not reactive and they only work at 'load time'

I've so removed the watcher for `setOptions` in our propsBinder and added back an `optionsMerger` function to mix options and `props.options` the function is trivial but I've added it because in v2 is a monster and I am afraid we will end up complicating it in v3 too

Finally I've chosen to add `options` as a prop directly on the vue components because is an `artificial` prop and not one coming from `leaflet`

### CODE REVIEW

**Comment by DonNicoJs** [comment]
@mikeu WDYT of this one?

**Comment by mikeu** [comment]
@DonNicoJs thanks for another big PR! On the whole it looks great, and definitely does fix the options issue. As you point out, it has a few important considerations though, so I just want to clarify a couple of points...

> setOptions used in Vue2Leaflet does.. nothing reactively! Each map element should be re-instantiated to pickup the behaviour (as per my tests) we also keep saying to people that the options are not reactive and they only work at 'load time'
> I've so removed the watcher for setOptions in our propsBinder

That was definitely a frustration with the old version. But am I mistaken that the current approach also still works that way? If I e.g. toggle `options: { riseOnHover }` on an existing marker in the playground, the behaviour of the map only uses the initial value. Is that still intended, for the moment at least? I thought the point of including `setOptions` was to make the options more reactive, but of course the options weren't actually hooked up before so I guess it turned out that it didn't work that way when you did add in the options?

As long as that's the intended behaviour right now then I'm fine to move ahead with this PR without making the options reactive in it, I just want to make sure it's working as you intended it to there.

>  and added back an optionsMerger function to mix options and props.options the function is trivial but I've added it because in v2 is a monster and I am afraid we will end up complicating it in v3 too

No problem with extracting a trivial function with the expectation its requirements will expand, but at the moment I am finding the order of operations feels slightly convoluted at first glance. We pass the props from a component into a function that builds the options for it as a mixture of Leaflet options and props, and then pass both the props and those options to a different function that further constructs the _actual_ options based on the previous mixture and `props.options`.

Is there a reason that we couldn't or shouldn't merge `props.options` into `options` somewhere inside the `componentSetup` methods in the `functions` directory so that when we say e.g. `const { options, methods } = markerSetup(props, ...)`, it returned `options` object already has the `props` correctly included? Perhaps simply by calling `optionsMerger` inside `componentSetup`?

> Finally I've chosen to add options as a prop directly on the vue components because is an artificial prop and not one coming from leaflet

By this you mean that is why you didn't put the `options: { type: Object, default: () => ({}) }` code into the `functions/component.js` files, right? I was going to suggest we move it there, probably to a single "base" file that all of the others call to get the `options` prop from. But if you think it shouldn't be there because it's not a true Leaflet option, I am OK with that, but wonder if it might still be worth DRYing up the repeated options definition. That could easily be another maintenance PR, or not worth it, WDYT?

**Comment by DonNicoJs** [comment]
@mikeu Thank you for the review!

Regarding `setOptions` the thing is that, even by normal leaflet usage `setOptions` do not 'redraw' anything! So using it on his own achieves basically nothing, the internal leaflet 'data' is updated but nothing changes on the map. This is why we should see (and encourage our users) `options` only as something to change the initial configuration and if they want it to be reactive they need to re-render with `v-if` on the component. 

After further thinking, I think you are right, and we should move all the `options` related things into `function/component.js` and move optionsMerger inside the functions and leave the component clean! On it!

**Comment by DonNicoJs** [comment]
@mikeu I've rewritten the whole thing by using a `component.js` file that exposes both the prop and optionsMerger, I've then wired it following this logic:

- component.js is our base class, everything should 'derive from it'
- if a component or a function do not import any other function (setup) it will import `component.j`

This way `options` is always wired everywhere.

I've used it in all the functions, but l-icon and l-map uses it directly

**Comment by mikeu** [comment]
@DonNicoJs Looks great! As per our discussion on discord this morning, I have reworked the base component slightly to have a `setup` function that returns the base `options` object. Now all actual components can pass their `props` to a "parent" `setup` function in the same way, whether that parent is `component.js` or a different more general Leaflet-based component.

I'm happy to merge it now, as long you approve of the updates :)

**Review by mikeu — APPROVED** [review]

**Pull request merged**
