### PR TITLE
Add basic docs and vitepress

### PR DESCRIPTION
**Pull request by DonNicoJs**
Part of #21

### CODE REVIEW

**Comment by DonNicoJs** [comment]
@mikeu I've added a very set of basic docs, WDYT?

**Comment by mikeu** [comment]
Will take a proper look at this later, have to run out right now. Looks great at first glance, though! Am I correct that vitepress is only for converting markdown to a static site, and for now the docs are still all manually typed? As in, it's not a replacement for vue-docgen, right?

**Review by mikeu — APPROVED** [review]
Great start! Should the output in `docs/.vitepress` also be included in the repo, or should it be added to .gitignore?

**Comment by DonNicoJs** [comment]
@mikeu I think the output is best left there for now! Let's revisit it when we have the final docs generation in progress! 

Merging this!

**Pull request merged**
