### PR TITLE
fix: Use invisible div as initial marker when slot is present

### PR DESCRIPTION
**Pull request by mikeu**
@imShara @lukkyjoe I believe I have come up with an alternative approach to resolving the blinking icon problem in #170.

First up, thank you for your help with this issue @lukkyjoe! Even though we couldn't merge your original solution because of its knock-on effects to other aspects of vue-leaflet's functionality, it was well researched and presented, and pointed me in the right direction to find another candidate solution.

This PR updates the logic when the `LMarker` component is mounted. If there is no `icon` property defined in the options but there _is_ a default slot present, then where it previously did nothing—leading to Leaflet's use of the default icon for a few cycles, as you identified—it now uses an empty, classless `divIcon` as the initial icon. In this way, the marker is completely invisible to the user until such time as the slot finishes rendering, and whatever `LIcon` or other content is within is can be displayed.

Would either or both of you be up for pulling this branch and confirming that when using it, you no longer see the blinking effect? I had basically the same technique as you @lukkyjoe, of spamming the toggle button in the repro, but as you say that is not the most scientific, especially given how much trouble I had getting the issue to manifest locally even under the old code. So while this approach makes sense to me, I'd appreciate some confirmation that it is working as intended for others as well!

### CODE REVIEW

**Comment by lukkyjoe** [comment]
hi @mikeu , 
I tested your branch and am confirming that I no longer see the blinking effect from my toggling. Nice idea to solve the issue without sacrificing the SSR/tree-shaking aspects!

**Comment by imShara** [comment]
Looks good, it should work, but I can't confirm that, because build of forked repo throws an error in my project. Don't digged in it, have no time, sorry.

**Comment by mikeu** [comment]
> Looks good, it should work, but I can't confirm that, because build of forked repo throws an error in my project. Don't digged in it, have no time, sorry.

Totally fair @imShara , but if I could ask a favour, would you happen to have time to copy and paste the error to me here so I can try to determine if it's at all related to this?

**Comment by imShara** [comment]
@mikeu it's unclear actually. Can you provide instruction how to build this module from your fork? Is just `npm install && npm build` enough?

Here is error, which breaks project when I replace vite-leaflet from npm with custom module. 
```
[Vue warn]: provide() can only be used inside setup(). 5 runtime-core.esm-bundler.js:6620:16
[Vue warn]: onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement. runtime-core.esm-bundler.js:6620:16
[Vue warn]: onBeforeUnmount is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement. runtime-core.esm-bundler.js:6620:16
[Vue warn]: Missing ref owner context. ref cannot be used on hoisted vnodes. A vnode with ref must be created inside the render function. 
  at <LMap ref="map" zoom=12 onUpdate:zoom=fn  ... > 
  at <Map class="" onCreatePoint=fn<createPoint> onOpenEventDetails=fn<openEventDetails> > 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App> runtime-core.esm-bundler.js:6620:16
```

**Comment by mikeu** [comment]
Thanks, @imShara . That doesn't look at first glance at least to be at all related to the minor changes this PR makes to the marker component.

For local testing, I work on vue-leaflet with yarn so I'll mention commands using it, but I believe they should all be very similar with npm. If you have the time and inclination to test this further it would be appreciated, but I totally understand if not!

How I set up my testing app was first to clone the vue-leaflet repo and run `yarn link` in its root, along with `yarn install`. I can then check out any branch I want to work with and run `yarn build`. I also created a new app for testing in another directory, e.g. `yarn create vite vue-leaflet-test`. In _that_ app, I `yarn link @vue-leaflet/vue-leaflet` to install the local linked copy to `node_modules`, along with `yarn add leaflet` and any other dependencies I may need.

At that point, I can start using vue-leaflet in the test app as you'd expect, and any changes made to the main vue-leaflet repo are automatically picked up in the test app once both have been rebuilt.

**Comment by edwh** [comment]
Just to say that this change works for me, so it would be nice if it was merged.

**Comment by rpastro** [comment]
@mikeu    Unfortunately this change broke the scenario where the marker has a tooltip and uses the default icon.  With v0.8.2 the marker is no longer visible in this case.  I'll open an issue for this.

```
    <l-marker
      v-for="(i, index) in items"
      :key="index"
      :lat-lng="[i.lat, i.lon]"
      @click="itemClicked(i)"
    >
      <l-tooltip>{{ i.tooltip }}</l-tooltip>
    </l-marker>
```

**Pull request merged**
